spring.application.name=FullStackProject
spring.datasource.url=jdbc:postgresql://localhost:5432/fsp
spring.datasource.username=postgres
spring.datasource.password=yugan@123
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8084